services:
  web:
    container_name: web
    build: ./
    restart: unless-stopped
    ports:
      - 8081:80
    volumes:
      - ./src:/var/www/html
    environment:
      - MYSQL_HOSTNAME=mysql_sql_to_rce
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=sql_to_rce_db
      - MYSQL_USER=vsl
      - MYSQL_PASSWORD=vsl_user_password

  mysql_sql_to_rce:
    container_name: mysql_sql_to_rce
    build: ./db
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=sql_to_rce_db
      - MYSQL_USER=vsl
      - MYSQL_PASSWORD=vsl_user_password
    volumes:
      - ./src:/var/www/html



    
